# 밑바닥부터 시작하는 딥러닝 실습 내용입니다.

In [1]:
import numpy as np

A=np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [3]:
np.ndim(A) # 몇 차원인지 확인

1

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

### 행렬의 곱

In [6]:
A=np.array([[1,2],[3,4]])

B=np.array([[5,6],[7,8]])

np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [8]:
A=np.array([[1,2,3],[4,5,6]])

B=np.array([[1,2],[3,4],[5,6]])

np.dot(A,B)

array([[22, 28],
       [49, 64]])

## 3층 신경망 구현하기

In [9]:
X=np.array([1.0,0.5])
W1=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1=np.array([0.1,0.2,0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)


In [10]:
A1 = np.dot(X,W1)+B1

In [14]:
def sigmoid(x):
    return 1 / (1 +np.exp(-x))

Z1=sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [17]:
W2= np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2= np.array([0.1,0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2=np.dot(Z1,W2)+B2
Z2=sigmoid(A2)
print(Z2)

(3,)
(3, 2)
(2,)
[0.62624937 0.7710107 ]


In [20]:
#마지막 출력층이 항등함수 일 경우

def identity_function(x):
    return x
W3=np.array([[0.1,0.3],[0.2,0.4]])
B3=np.array([0.1,0.2])

A3= np.dot(Z2,W3)+B3
Y=identity_function(A3)
Y

array([0.31682708, 0.69627909])

### 출력층에서 소프트맥스 함수 사용하기

합이 1이기 때문에 분류에서 많이 사용된다.

In [21]:
a=np.array([0.3,2.9,4.0])
exp_a=np.exp(a)
print(exp_a)


[ 1.34985881 18.17414537 54.59815003]


In [22]:
sum_exp_a=np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [23]:
y=exp_a/sum_exp_a

In [24]:
print(y)

[0.01821127 0.24519181 0.73659691]


In [25]:
#오버플로를 방지하기 위해서 분모 분자에 상수를 빼준다.
def softmax(a):
    c=np.max(a)
    exp_a=np.exp(a-c)
    y=exp_a/sum_exp_a
    return y